import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import {siteConfig} from "@/config/site.config";
import Footer from "@/components/footer";
import GlobalSmoothScrool from "@/components/GlobalSmoothScrool";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Autorin Monika Meier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {general} = siteConfig

  return (
    <html
      lang="de"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <header className="w-full z-100 fixed top-0">
        <Navbar/>
      </header>
      <GlobalSmoothScrool>
        <div className="flex min-h-screen flex-col pt-20">
          <main className="w-full grow">{children}</main>
          <Footer/>
        </div>
      </GlobalSmoothScrool>
      </body>
    </html>
  );
}
